### ISSUE TITLE
Exception thrown in case the RecordEvent is called when the sdk is not initialized

### ISSUE THREAD

**Issue by ehudros** [deltaDNA/unity-sdk#1]
It seems like the SDK throws an exception whenever RecordEvent is called without the SDK being properly initialized. I found that a bit aggressive and unpredictable (in my case the unhandled exception broke some subsequent logic). A better alternative in my opinion would be to silently fail and log out errors to the console with Debug.LogError. 
Not initializing the SDK is something that can happen either during development (when working in the editor) or even by design in a released version.

Cheers :)

**Comment by dwxw** [comment]
Yes, the SDK will throw an exception if you try and use it without calling StartSDK.  That's by design.  The team have had the argument about throwing vs logging plenty of times, but felt in a few fundamental cases it was helpful to point out the SDK is not being used correctly.  It could just as easily be a problem the other way where folk are wondering why no data is being sent to us only to find they hadn't started the SDK.

I would recommend just starting the SDK.  It works fine in the editor.  On our platform each game has a dev and a live environment.  During development you should point the SDK at its dev environment which lets you separate out events from dev builds.  Have a look through the [setup](http://docs.deltadna.com/reference/setup/events/) docs for more info.

**Comment by ehudros** [comment]
Fair enough, that's a valid design decision. Might be worth adding it to the docs, since I think other developers may also find this a bit unexpected.
In any case thanks for the quick response!

**Comment by dwxw** [comment]
That's a fair point that's it's not very obvious.  I'll beef up the documentation some more.
